

import ProductLGA from "../../../images/product/lg-a.jpg";
import ProductLGB from "../../../images/product/lg-b.jpg";
import ProductLGC from "../../../images/product/lg-c.jpg";
import ProductLGD from "../../../images/product/lg-d.jpg";
import ProductLGE from "../../../images/product/lg-e.jpg";
import ProductLGF from "../../../images/product/lg-f.jpg";
import ProductLGG from "../../../images/product/lg-g.jpg";
import ProductLGH from "../../../images/product/lg-h.jpg";

export const productData = [
  {
    id: 1,
    name: "Sinan Bakış",

    checked: false,
    email: "sinanbakis@gmail.com",
    phone: "+90 507 855 55 55",
    category: "Kategori",
    ticket: "Etiket Adı",
    city: "Şehir",
    representative: {
      avatarBg: "purple",
      name: "Temsilci"
    },
    status: "Aktif",
  },
  {
    id: 2,
    name: "Sinan Bakış",

    checked: false,
    email: "sinanbakis@gmail.com",
    phone: "+90 507 855 55 55",
    category: "Kategori",
    ticket: "Etiket Adı",
    city: "Şehir",
    representative: {
      avatarBg: "purple",
      name: "Temsilci"
    },
    status: "Aktif",
  },
  {
    id: 3,
    name: "Sinan Bakış",

    checked: false,
    email: "sinanbakis@gmail.com",
    phone: "+90 507 855 55 55",
    category: "Kategori",
    ticket: "Etiket Adı",
    city: "Şehir",
    representative: {
      avatarBg: "purple",
      name: "Temsilci"
    },
    status: "Aktif",
  },
  {
    id: 4,
    name: "Sinan Bakış",

    checked: false,
    email: "sinanbakis@gmail.com",
    phone: "+90 507 855 55 55",
    category: "Kategori",
    ticket: "Etiket Adı",
    city: "Şehir",
    representative: {
      avatarBg: "purple",
      name: "Temsilci"
    },
    status: "Aktif",
  },
  {
    id: 5,
    name: "Sinan Bakış",

    checked: false,
    email: "sinanbakis@gmail.com",
    phone: "+90 507 855 55 55",
    category: "Kategori",
    ticket: "Etiket Adı",
    city: "Şehir",
    representative: {
      avatarBg: "purple",
      name: "Temsilci"
    },
    status: "Aktif",
  },
  {
    id: 6,
    name: "Sinan Bakış",

    checked: false,
    email: "sinanbakis@gmail.com",
    phone: "+90 507 855 55 55",
    category: "Kategori",
    ticket: "Etiket Adı",
    city: "Şehir",
    representative: {
      avatarBg: "purple",
      name: "Temsilci"
    },
    status: "Aktif",
  },
  {
    id: 7,
    name: "Sinan Bakış",

    checked: false,
    email: "sinanbakis@gmail.com",
    phone: "+90 507 855 55 55",
    category: "Kategori",
    ticket: "Etiket Adı",
    city: "Şehir",
    representative: {
      avatarBg: "purple",
      name: "Temsilci"
    },
    status: "Aktif",
  },
  {
    id: 8,
    name: "Sinan Bakış",

    checked: false,
    email: "sinanbakis@gmail.com",
    phone: "+90 507 855 55 55",
    category: "Kategori",
    ticket: "Etiket Adı",
    city: "Şehir",
    representative: {
      avatarBg: "purple",
      name: "Temsilci"
    },
    status: "Aktif",
  },
  {
    id: 9,
    name: "Sinan Bakış",

    checked: false,
    email: "sinanbakis@gmail.com",
    phone: "+90 507 855 55 55",
    category: "Kategori",
    ticket: "Etiket Adı",
    city: "Şehir",
    representative: {
      avatarBg: "purple",
      name: "Temsilci"
    },
    status: "Aktif",
  },
  {
    id: 10,
    name: "Sinan Bakış",

    checked: false,
    email: "sinanbakis@gmail.com",
    phone: "+90 507 855 55 55",
    category: "Kategori",
    ticket: "Etiket Adı",
    city: "Şehir",
    representative: {
      avatarBg: "purple",
      name: "Temsilci"
    },
    status: "Aktif",
  },
  {
    id: 11,
    name: "Sinan Bakış",

    checked: false,
    email: "sinanbakis@gmail.com",
    phone: "+90 507 855 55 55",
    category: "Kategori",
    ticket: "Etiket Adı",
    city: "Şehir",
    representative: {
      avatarBg: "purple",
      name: "Temsilci"
    },
    status: "Aktif",
  },
  {
    id: 12,
    name: "Sinan Bakış",

    checked: false,
    email: "sinanbakis@gmail.com",
    phone: "+90 507 855 55 55",
    category: "Kategori",
    ticket: "Etiket Adı",
    city: "Şehir",
    representative: {
      avatarBg: "purple",
      name: "Temsilci"
    },
    status: "Aktif",
  },
  {
    id: 13,
    name: "Sinan Bakış",

    checked: false,
    email: "sinanbakis@gmail.com",
    phone: "+90 507 855 55 55",
    category: "Kategori",
    ticket: "Etiket Adı",
    city: "Şehir",
    representative: {
      avatarBg: "purple",
      name: "Temsilci"
    },
    status: "Aktif",
  },
  {
    id: 14,
    name: "Sinan Bakış",

    checked: false,
    email: "sinanbakis@gmail.com",
    phone: "+90 507 855 55 55",
    category: "Kategori",
    ticket: "Etiket Adı",
    city: "Şehir",
    representative: {
      avatarBg: "purple",
      name: "Temsilci"
    },
    status: "Aktif",
  },
  {
    id: 15,
    name: "Sinan Bakış",

    checked: false,
    email: "sinanbakis@gmail.com",
    phone: "+90 507 855 55 55",
    category: "Kategori",
    ticket: "Etiket Adı",
    city: "Şehir",
    representative: {
      avatarBg: "purple",
      name: "Temsilci"
    },
    status: "Aktif",
  },
  {
    id: 16,
    name: "Sinan Bakış",

    checked: false,
    email: "sinanbakis@gmail.com",
    phone: "+90 507 855 55 55",
    category: "Kategori",
    ticket: "Etiket Adı",
    city: "Şehir",
    representative: {
      avatarBg: "purple",
      name: "Temsilci"
    },
    status: "Aktif",
  },
  {
    id: 17,
    name: "Sinan Bakış",

    checked: false,
    email: "sinanbakis@gmail.com",
    phone: "+90 507 855 55 55",
    category: "Kategori",
    ticket: "Etiket Adı",
    city: "Şehir",
    representative: {
      avatarBg: "purple",
      name: "Temsilci"
    },
    status: "Aktif",
  },
  {
    id: 18,
    name: "Sinan Bakış",

    checked: false,
    email: "sinanbakis@gmail.com",
    phone: "+90 507 855 55 55",
    category: "Kategori",
    ticket: "Etiket Adı",
    city: "Şehir",
    representative: {
      avatarBg: "purple",
      name: "Temsilci"
    },
    status: "Aktif",
  },
  {
    id: 19,
    name: "Sinan Bakış",

    checked: false,
    email: "sinanbakis@gmail.com",
    phone: "+90 507 855 55 55",
    category: "Kategori",
    ticket: "Etiket Adı",
    city: "Şehir",
    representative: {
      avatarBg: "purple",
      name: "Temsilci"
    },
    status: "Aktif",
  },
  {
    id: 20,
    name: "Sinan Bakış",

    checked: false,
    email: "sinanbakis@gmail.com",
    phone: "+90 507 855 55 55",
    category: "Kategori",
    ticket: "Etiket Adı",
    city: "Şehir",
    representative: {
      avatarBg: "purple",
      name: "Temsilci"
    },
    status: "Aktif",
  },
];

export const productCardData = [
  {
    id: 0,
    img: ProductLGA,
    new: true,
    hot: false,
    like: false,
    cart: false,
    slider: [
      { id: 0, img: ProductLGA },
      { id: 1, img: ProductLGB },
      { id: 2, img: ProductLGC },
      { id: 3, img: ProductLGD },
      { id: 4, img: ProductLGE },
      { id: 5, img: ProductLGF },
    ],
    name: "Smart Watch",
    title: "Classy Modern Smart Watch",
    type: "watch",
    modelNumber: "",
    prevPrice: 350,
    newPrice: 324,
  },
  {
    id: 1,
    img: ProductLGB,
    new: false,
    hot: false,
    like: false,
    cart: false,
    slider: [
      { id: 0, img: ProductLGB },
      { id: 1, img: ProductLGA },
      { id: 2, img: ProductLGC },
      { id: 3, img: ProductLGD },
      { id: 4, img: ProductLGE },
      { id: 5, img: ProductLGF },
    ],
    type: "phone",
    modelNumber: "",
    name: "Vintage Phone",
    title: "White Vintage Phone",
    prevPrice: 209,
    newPrice: 119,
  },
  {
    id: 2,
    img: ProductLGC,
    new: false,
    hot: true,
    like: false,
    cart: false,
    slider: [
      { id: 0, img: ProductLGC },
      { id: 1, img: ProductLGA },
      { id: 2, img: ProductLGB },
      { id: 3, img: ProductLGD },
      { id: 4, img: ProductLGE },
      { id: 5, img: ProductLGF },
    ],
    type: "headphone",
    modelNumber: "",
    name: "Headphones",
    title: "Black Wireless Headphone",
    prevPrice: 119,
    newPrice: 89,
  },
  {
    id: 3,
    img: ProductLGD,
    new: false,
    hot: false,
    like: false,
    cart: false,
    slider: [
      { id: 0, img: ProductLGD },
      { id: 1, img: ProductLGA },
      { id: 2, img: ProductLGB },
      { id: 3, img: ProductLGC },
      { id: 4, img: ProductLGE },
      { id: 5, img: ProductLGF },
    ],
    type: "watch",
    modelNumber: "",
    name: "Smart Watch",
    title: "Modular Smart Watch",
    prevPrice: 169,
    newPrice: 129,
  },
  {
    id: 4,
    img: ProductLGE,
    new: false,
    hot: false,
    like: false,
    cart: false,
    slider: [
      { id: 0, img: ProductLGE },
      { id: 1, img: ProductLGA },
      { id: 2, img: ProductLGB },
      { id: 3, img: ProductLGC },
      { id: 4, img: ProductLGD },
      { id: 5, img: ProductLGF },
    ],
    type: "headphone",
    modelNumber: "",
    name: "Headphone",
    title: "White Wireless Headphones",
    prevPrice: 109,
    newPrice: 78,
  },
  {
    id: 5,
    img: ProductLGF,
    new: false,
    hot: false,
    like: false,
    cart: false,
    slider: [
      { id: 0, img: ProductLGF },
      { id: 1, img: ProductLGA },
      { id: 2, img: ProductLGB },
      { id: 3, img: ProductLGC },
      { id: 4, img: ProductLGD },
      { id: 5, img: ProductLGE },
    ],
    type: "phone",
    modelNumber: "",
    name: "Phone",
    title: "Black Android Phone",
    prevPrice: null,
    newPrice: 329,
  },
  {
    id: 6,
    img: ProductLGG,
    new: false,
    hot: false,
    like: false,
    cart: false,
    slider: [
      { id: 0, img: ProductLGG },
      { id: 1, img: ProductLGB },
      { id: 2, img: ProductLGC },
      { id: 3, img: ProductLGD },
      { id: 4, img: ProductLGE },
      { id: 5, img: ProductLGF },
    ],
    type: "watch",
    modelNumber: "",
    name: "Smart Watch",
    title: "Modern Smart Watch",
    prevPrice: 200,
    newPrice: 179,
  },
  {
    id: 7,
    img: ProductLGH,
    new: false,
    hot: true,
    like: false,
    cart: false,
    slider: [
      { id: 0, img: ProductLGH },
      { id: 1, img: ProductLGB },
      { id: 2, img: ProductLGC },
      { id: 3, img: ProductLGD },
      { id: 4, img: ProductLGE },
      { id: 5, img: ProductLGF },
    ],
    type: "bundle",
    modelNumber: "",
    name: "Bundle",
    title: "Gadget Bundle",
    prevPrice: 609,
    newPrice: 412,
  },
  {
    id: 8,
    img: ProductLGA,
    new: true,
    hot: false,
    like: false,
    cart: false,
    slider: [
      { id: 0, img: ProductLGA },
      { id: 1, img: ProductLGB },
      { id: 2, img: ProductLGC },
      { id: 3, img: ProductLGD },
      { id: 4, img: ProductLGE },
      { id: 5, img: ProductLGF },
    ],
    name: "Modern Watch",
    title: "Modern Smart Watch",
    type: "watch",
    modelNumber: "",
    prevPrice: 350,
    newPrice: 324,
  },
  {
    id: 9,
    img: ProductLGB,
    new: false,
    hot: false,
    like: false,
    cart: false,
    slider: [
      { id: 0, img: ProductLGB },
      { id: 1, img: ProductLGA },
      { id: 2, img: ProductLGC },
      { id: 3, img: ProductLGD },
      { id: 4, img: ProductLGE },
      { id: 5, img: ProductLGF },
    ],
    type: "phone",
    modelNumber: "",
    name: "Phone",
    title: "Grey Vintage Phone",
    prevPrice: 209,
    newPrice: 119,
  },
  {
    id: 10,
    img: ProductLGF,
    new: false,
    hot: false,
    like: false,
    cart: false,
    slider: [
      { id: 0, img: ProductLGF },
      { id: 1, img: ProductLGB },
      { id: 2, img: ProductLGC },
      { id: 3, img: ProductLGD },
      { id: 4, img: ProductLGE },
      { id: 5, img: ProductLGG },
    ],
    type: "phone",
    modelNumber: "",
    name: "Phone",
    title: "Grey Phone",
    prevPrice: null,
    newPrice: 329,
  },
  {
    id: 11,
    img: ProductLGG,
    new: false,
    hot: false,
    like: false,
    cart: false,
    type: "watch",
    slider: [
      { id: 0, img: ProductLGG },
      { id: 1, img: ProductLGB },
      { id: 2, img: ProductLGC },
      { id: 3, img: ProductLGD },
      { id: 4, img: ProductLGE },
      { id: 5, img: ProductLGF },
    ],
    modelNumber: "",
    name: "Smart Watch",
    title: "Modern Watch",
    prevPrice: 200,
    newPrice: 179,
  },
  {
    id: 12,
    img: ProductLGH,
    new: false,
    hot: true,
    like: false,
    cart: false,
    slider: [
      { id: 0, img: ProductLGH },
      { id: 1, img: ProductLGB },
      { id: 2, img: ProductLGC },
      { id: 3, img: ProductLGD },
      { id: 4, img: ProductLGE },
      { id: 5, img: ProductLGF },
    ],
    type: "bundle",
    modelNumber: "",
    name: "Quality Bundle",
    title: "Quality Gadget Bundle",
    prevPrice: 609,
    newPrice: 412,
  },
  {
    id: 13,
    img: ProductLGC,
    new: false,
    hot: true,
    like: false,
    cart: false,
    slider: [
      { id: 0, img: ProductLGC },
      { id: 1, img: ProductLGB },
      { id: 2, img: ProductLGH },
      { id: 3, img: ProductLGD },
      { id: 4, img: ProductLGE },
      { id: 5, img: ProductLGF },
    ],
    type: "headphone",
    modelNumber: "",
    name: "Headphones",
    title: "Wireless Headphone",
    prevPrice: 119,
    newPrice: 89,
  },
  {
    id: 14,
    img: ProductLGD,
    new: false,
    hot: false,
    like: false,
    cart: false,
    slider: [
      { id: 0, img: ProductLGD },
      { id: 1, img: ProductLGB },
      { id: 2, img: ProductLGC },
      { id: 3, img: ProductLGA },
      { id: 4, img: ProductLGE },
      { id: 5, img: ProductLGF },
    ],
    type: "watch",
    modelNumber: "",
    name: "Watch",
    title: "Modular Watch",
    prevPrice: 169,
    newPrice: 129,
  },
  {
    id: 15,
    img: ProductLGE,
    new: false,
    hot: false,
    like: false,
    cart: false,
    slider: [
      { id: 0, img: ProductLGE },
      { id: 1, img: ProductLGB },
      { id: 2, img: ProductLGC },
      { id: 3, img: ProductLGD },
      { id: 4, img: ProductLGH },
      { id: 5, img: ProductLGF },
    ],
    type: "headphone",
    modelNumber: "",
    name: "Headphone",
    title: "White Headphones",
    prevPrice: 109,
    newPrice: 78,
  },
  {
    id: 16,
    img: ProductLGF,
    new: false,
    hot: false,
    like: false,
    cart: false,
    slider: [
      { id: 0, img: ProductLGF },
      { id: 1, img: ProductLGB },
      { id: 2, img: ProductLGC },
      { id: 3, img: ProductLGD },
      { id: 4, img: ProductLGE },
      { id: 5, img: ProductLGG },
    ],
    type: "phone",
    modelNumber: "",
    name: "Phone",
    title: "Grey Phone",
    prevPrice: null,
    newPrice: 329,
  },
  {
    id: 17,
    img: ProductLGG,
    new: false,
    hot: false,
    like: false,
    cart: false,
    slider: [
      { id: 0, img: ProductLGG },
      { id: 1, img: ProductLGB },
      { id: 2, img: ProductLGC },
      { id: 3, img: ProductLGD },
      { id: 4, img: ProductLGE },
      { id: 5, img: ProductLGF },
    ],
    type: "watch",
    modelNumber: "",
    name: "Smart Watch",
    title: "Modern Watch",
    prevPrice: 200,
    newPrice: 179,
  },
  {
    id: 18,
    img: ProductLGH,
    new: false,
    hot: true,
    like: false,
    cart: false,
    slider: [
      { id: 0, img: ProductLGH },
      { id: 1, img: ProductLGB },
      { id: 2, img: ProductLGC },
      { id: 3, img: ProductLGD },
      { id: 4, img: ProductLGE },
      { id: 5, img: ProductLGF },
    ],
    type: "bundle",
    modelNumber: "",
    name: "Quality Bundle",
    title: "Quality Gadget Bundle",
    prevPrice: 609,
    newPrice: 412,
  },
];

export const categoryOptions = [
  {
    value: "Firma1",
    label: "Firma1",
  },
  {
    value: "Firma2",
    label: "Firma2",
  },
  {
    label: "Firma3",
    value: "Firma3",
  },
  {
    label: "Firma4",
    value: "Firma4",
  },
  {
    label: "Firma5",
    value: "Firma5",
  },

];
